version: '3.3'

services:
  auth_service:
    container_name: auth-node
    build:
      dockerfile: Dockerfile
      context: ./
    tty: true
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - '3001:3001'
      - '9229:9229'

volumes:
  node_modules:

networks:
  default:
    external:
      name: local_network
